branch-defaults:
  main:
    environment: auto-pop-backend-v1-dev
environment-defaults:
  auto-pop-backend-v1-dev:
    branch: null
    repository: null
global:
  application_name: auto-pop-backend-v1
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
