branch-defaults:
  feature/aws-deploy:
    environment: auto-pop-server-dev
    group_suffix: null
global:
  application_name: auto-pop-server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
