name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
    # paths:
    #   - "apps/backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Deploy to Elastic Beanstalk
        run: eb deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
