name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths-ignore:
      - "apps/browser-extension/**"
      - "**/.gitignore"
      - "**/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # Could build and push the app image to docker hub here.
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.EB_ENVIRONMENT_NAME }}:latest

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**" "**.git**" "**.github**" "**.env**" "**.DS_Store**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ env.VERSION }}
          region: eu-west-2
          deployment_package: deploy.zip
